[project]
name = "novel-action-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "huggingface_hub",
    "numpy",
    "opencv-python",
    "pandas",
    "pillow",
    "scikit-learn",
    "scipy",
    "torch",
    "torchaudio",
    "torchvision",
    "transformers",
]
